### PR TITLE
Allow restore network to have network connectivity

### PR DESCRIPTION
**Pull request by huikang**
Reuse the endpoint of the checkpointed container when restore.
Pass veth pair name to ciur when restore a checkpointed container.

Signed-off-by: Hui Kang hkang.sunysb@gmail.com

### CODE REVIEW

**Comment by boucher** [comment]
hey @huikang, I had to rebase again, and unfortunately this code no longer works. Even adapted to use https://github.com/docker/libnetwork/pull/518, the network no longer functions after a restore. I haven't been able to track down the problem yet.

**Comment by huikang** [comment]
@boucher Thanks for letting me know. I will look at the problem soon.

**Comment by huikang** [comment]
@boucher I have been able to re-created the patch as of here.
https://github.com/boucher/docker/pull/19

Maybe we should close this PR and move the discussion over there. Thanks.

**Comment by boucher** [comment]
Ok, closing this.

**Pull request closed without merging**
