### PR TITLE
Set default checkpointed images under /var/lib/docker

### PR DESCRIPTION
**Pull request by huikang**
/var/run/ is reset after host reboot

Docker-DCO-1.1-Signed-off-by: Hui Kang hkang.sunysb@gmail.com (github: huikang)

### CODE REVIEW

**Comment by huikang** [comment]
@boucher I have closed the previous PR. Could you review this one? Thanks.

**Comment by boucher** [comment]
So, this seems to work ok, but I'm a bit worried about the sort of unspecified behavior for multiple checkpoint/restore pairs. It seems like currently criu just overwrites any file that is already present in the directory. It might be nice to explicitly delete the folder after restore? Or prior to checkpointing if it exists? I'm not sure. Similarly, with logs, maybe we should be appending a timestamp to the path?

**Comment by huikang** [comment]
@boucher I do not think this PR addresses the issue your proposing. This PR sets the default criu images location to prevent criu image loss after rebooting the host. The PR still has some issue, because it does not deal with the runC metadata file of the container (i.e., /var/run/docker/.../state.json). When this metafile under /var/run is lost, checkpointed container still can not be restored. I need to make some changes.

Regarding the multiple checkpoint issues, I remember some earlier version deletes the criu image after restore. Do you think we should discuss this in a separate thread.

**Comment by huikang** [comment]
Ping @boucher and @SaiedKazemi
I think we should completely remove /var/run/docker/execdrive/<container ID> for a checkpointed container. Three reasons:
1. This runC directory will be removed after host reboot. In that case, a checkpointed container cannot be restore.
2. The metadata file (state.json) under this directory can be loaded by calling d.factory.Create(c.ID, config) like force-restore=true. Therefore, restoring a checkpointed container does not need depend on an existing metadata file.
3. As this PR does, the default criu image and work directory will be moved to a more persistent place, e.g., /var/lib/docker.

What do you think? - Hui

**Comment by SaiedKazemi** [comment]
@huikang @boucher 
The image files that CRIU generates definitely have to be stored on persistent disk so they won't be deleted upon rebooting.  In 1.5, I stored them in /var/lib/docker/containers/<CID>/criu_img directory and Docker successfully finds and restores after reboot.  When C/R was added to libcontainer, this place changed to make it independent of Docker but it's possible to pass the location of where the image files should go.  So you should be able to use a persistent location.

**Comment by huikang** [comment]
@SaiedKazemi 
I agreed that everything about a checkpointed container should be on a persistent disk.
So this PR sets the default criu image location to /var/lib/docker, instead of /var/run.

@boucher would you consider merging this PR? Thanks.

**Comment by boucher** [comment]
@huikang I think you misunderstood my question. I don't understand how state.json is coming into play here, its not necessary for restoring as far as I understand. 

In any case, I agree that this is better than what we have, so I'll merge it in. I just think we should possibly go further.

**Comment by huikang** [comment]
@boucher Oh, I see. The state.json is necessary; you could try deleting it and "docker restore" will fail.

Ideally, state.json should be in a persistent disk as well. However, docker daemon actually does not need state.json (just like docker stop and docker start) because state.json is created by docker daemon. So checkpoint may delete that state.json and reloads it during restore by calling d.factory.Create(c.ID, config) like force-restore=true.

**Pull request merged**
