### PR TITLE
Add back missing files for restoring container

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang hkang.sunysb@gmail.com

### CODE REVIEW

**Comment by boucher** [comment]
This pull request is really just a placeholder for my to keep track of next steps, after my existing real pull request has been merged or is at least closer to it.

**Comment by huikang** [comment]
Ok. I saw you send a PR about this branch. thanks.

**Comment by boucher** [comment]
This is the PR I'm currently tracking in docker land: https://github.com/docker/docker/pull/13442

**Comment by huikang** [comment]
cool. Thanks.

**Pull request closed without merging**
