### PR TITLE
Change Checkpointed state in config file to true after checkpoing

### PR DESCRIPTION
**Pull request by huikang**
This patch updates container config file so that checkpointed state is kept
after docker daemon restarted.

Docker-DCO-1.1-Signed-off-by: Hui Kang hkang.sunysb@gmail.com (github: huikang)

### CODE REVIEW

**Comment by huikang** [comment]
@boucher do you have a minute to review the patch? Thanks.

**Comment by boucher** [comment]
Looks good. I may wait to merge anything in until after I'm able to get the latest libcontainer merged into docker.

**Comment by boucher** [comment]
Could you rebase this branch on top of my latest rebase?

**Comment by huikang** [comment]
Sure, will do now.

**Comment by huikang** [comment]
Please ignore this due to the conflict. Will open another one

**Pull request closed without merging**
